name: py_runner
description: واجهة تطبيق تشغيل سكربتات بايثون (نسخة تجريبية)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  material_ui: ^1.0.0
  url_launcher: ^6.3.2
  # الجزء الأول B: الملفات والتخزين
  path_provider: ^2.1.5
  permission_handler: ^13.0.2
  file_picker: ^13.1.0
  shared_preferences: ^2.5.3
  device_info_plus: ^13.1.0

flutter:
  uses-material-design: true
